services:
  - type: web
    name: backend-app
    env: docker
    repo: https://github.com/Johnki1/billing-app.git
    plan: free
    rootDir: Backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ""
      - key: SPRING_DATASOURCE_USERNAME
        value: ""
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: CLOUDINARY_URL
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
- type: web     
  name: frontend-app
  env: static
  repo: https://github.com/Johnki1/billing-app.git
  plan: free
  rootDir: Frontend
  buildCommand: npm install && npm run build
  staticPublishPath: dist
  envVars:
    - key: VITE_API_URL
      value: ""
